USE sistema_vagas;

INSERT INTO habilidades (nome, categoria) VALUES

-- Categoria 1: Comportamental (Soft Skills)
('Comunicação Assertiva', 'Comportamental (Soft Skills)'),
('Inteligência Emocional', 'Comportamental (Soft Skills)'),
('Resolução de Conflitos', 'Comportamental (Soft Skills)'),
('Liderança', 'Comportamental (Soft Skills)'),
('Trabalho em Equipe', 'Comportamental (Soft Skills)'),
('Adaptabilidade', 'Comportamental (Soft Skills)'),
('Gerenciamento de Tempo', 'Comportamental (Soft Skills)'),
('Proatividade', 'Comportamental (Soft Skills)'),
('Pensamento Crítico', 'Comportamental (Soft Skills)'),
('Criatividade', 'Comportamental (Soft Skills)'),
('Resiliência', 'Comportamental (Soft Skills)'),
('Empatia', 'Comportamental (Soft Skills)'),
('Negociação (Interpessoal)', 'Comportamental (Soft Skills)'),
('Feedback (Dar e Receber)', 'Comportamental (Soft Skills)'),
('Oratória', 'Comportamental (Soft Skills)'),
('Escuta Ativa', 'Comportamental (Soft Skills)'),
('Persuasão', 'Comportamental (Soft Skills)'),
('Paciência', 'Comportamental (Soft Skills)'),
('Foco', 'Comportamental (Soft Skills)'),
('Organização Pessoal', 'Comportamental (Soft Skills)'),
('Autogestão', 'Comportamental (Soft Skills)'),
('Tomada de Decisão', 'Comportamental (Soft Skills)'),
('Delegação', 'Comportamental (Soft Skills)'),
('Motivação', 'Comportamental (Soft Skills)'),
('Flexibilidade Cognitiva', 'Comportamental (Soft Skills)'),
('Curiosidade', 'Comportamental (Soft Skills)'),
('Mentalidade de Crescimento (Growth Mindset)', 'Comportamental (Soft Skills)'),
('Colaboração', 'Comportamental (Soft Skills)'),
('Responsabilidade', 'Comportamental (Soft Skills)'),
('Ética Profissional', 'Comportamental (Soft Skills)'),

-- Categoria 2: Tecnologia da Informação (TI) e Programação
('Python', 'Tecnologia da Informação (TI) e Programação'),
('JavaScript', 'Tecnologia da Informação (TI) e Programação'),
('Java', 'Tecnologia da Informação (TI) e Programação'),
('C#', 'Tecnologia da Informação (TI) e Programação'),
('PHP', 'Tecnologia da Informação (TI) e Programação'),
('Go (Golang)', 'Tecnologia da Informação (TI) e Programação'),
('Ruby', 'Tecnologia da Informação (TI) e Programação'),
('Swift', 'Tecnologia da Informação (TI) e Programação'),
('Kotlin', 'Tecnologia da Informação (TI) e Programação'),
('TypeScript', 'Tecnologia da Informação (TI) e Programação'),
('HTML5', 'Tecnologia da Informação (TI) e Programação'),
('CSS3', 'Tecnologia da Informação (TI) e Programação'),
('React.js', 'Tecnologia da Informação (TI) e Programação'),
('Angular', 'Tecnologia da Informação (TI) e Programação'),
('Vue.js', 'Tecnologia da Informação (TI) e Programação'),
('Node.js', 'Tecnologia da Informação (TI) e Programação'),
('Django', 'Tecnologia da Informação (TI) e Programação'),
('Flask', 'Tecnologia da Informação (TI) e Programação'),
('Spring Boot', 'Tecnologia da Informação (TI) e Programação'),
('.NET Core', 'Tecnologia da Informação (TI) e Programação'),
('Git', 'Tecnologia da Informação (TI) e Programação'),
('GitHub/GitLab', 'Tecnologia da Informação (TI) e Programação'),
('SQL', 'Tecnologia da Informação (TI) e Programação'),
('NoSQL (MongoDB, Redis)', 'Tecnologia da Informação (TI) e Programação'),
('Arquitetura de Microsserviços', 'Tecnologia da Informação (TI) e Programação'),
('APIs (REST, GraphQL)', 'Tecnologia da Informação (TI) e Programação'),
('Programação Orientada a Objetos (POO)', 'Tecnologia da Informação (TI) e Programação'),
('Programação Funcional', 'Tecnologia da Informação (TI) e Programação'),
('Testes Unitários', 'Tecnologia da Informação (TI) e Programação'),
('Desenvolvimento Mobile (React Native, Flutter)', 'Tecnologia da Informação (TI) e Programação'),

-- Categoria 3: Análise de Dados (Data Analytics)
('SQL (Avançado)', 'Análise de Dados (Data Analytics)'),
('Python (Pandas, NumPy)', 'Análise de Dados (Data Analytics)'),
('R', 'Análise de Dados (Data Analytics)'),
('Power BI', 'Análise de Dados (Data Analytics)'),
('Tableau', 'Análise de Dados (Data Analytics)'),
('Google Data Studio', 'Análise de Dados (Data Analytics)'),
('Excel (Avançado)', 'Análise de Dados (Data Analytics)'),
('Machine Learning', 'Análise de Dados (Data Analytics)'),
('Estatística', 'Análise de Dados (Data Analytics)'),
('Visualização de Dados', 'Análise de Dados (Data Analytics)'),
('ETL (Extract, Transform, Load)', 'Análise de Dados (Data Analytics)'),
('Data Warehousing', 'Análise de Dados (Data Analytics)'),
('Business Intelligence (BI)', 'Análise de Dados (Data Analytics)'),
('Mineração de Dados (Data Mining)', 'Análise de Dados (Data Analytics)'),
('Big Data (Hadoop, Spark)', 'Análise de Dados (Data Analytics)'),
('Engenharia de Dados', 'Análise de Dados (Data Analytics)'),
('Modelagem Preditiva', 'Análise de Dados (Data Analytics)'),
('Testes A/B', 'Análise de Dados (Data Analytics)'),
('Storytelling com Dados', 'Análise de Dados (Data Analytics)'),
('Análise de Cohort', 'Análise de Dados (Data Analytics)'),
('Análise de Funil', 'Análise de Dados (Data Analytics)'),
('Google Analytics', 'Análise de Dados (Data Analytics)'),
('Processamento de Linguagem Natural (PLN)', 'Análise de Dados (Data Analytics)'),
('Limpeza de Dados', 'Análise de Dados (Data Analytics)'),
('Coleta de Dados', 'Análise de Dados (Data Analytics)'),
('Análise de Regressão', 'Análise de Dados (Data Analytics)'),
('Web Scraping', 'Análise de Dados (Data Analytics)'),
('SAS', 'Análise de Dados (Data Analytics)'),
('QlikView', 'Análise de Dados (Data Analytics)'),
('Modelagem de Dados', 'Análise de Dados (Data Analytics)'),

-- Categoria 4: Design e Experiência do Usuário (UX/UI)
('Figma', 'Design e Experiência do Usuário (UX/UI)'),
('Adobe XD', 'Design e Experiência do Usuário (UX/UI)'),
('Sketch', 'Design e Experiência do Usuário (UX/UI)'),
('Design Thinking', 'Design e Experiência do Usuário (UX/UI)'),
('Pesquisa com Usuários (User Research)', 'Design e Experiência do Usuário (UX/UI)'),
('Teste de Usabilidade', 'Design e Experiência do Usuário (UX/UI)'),
('Prototipação (Baixa e Alta Fidelidade)', 'Design e Experiência do Usuário (UX/UI)'),
('Wireframing', 'Design e Experiência do Usuário (UX/UI)'),
('Arquitetura da Informação', 'Design e Experiência do Usuário (UX/UI)'),
('Jornada do Usuário (User Journey Mapping)', 'Design e Experiência do Usuário (UX/UI)'),
('Criação de Personas', 'Design e Experiência do Usuário (UX/UI)'),
('Design de Interação (IxD)', 'Design e Experiência do Usuário (UX/UI)'),
('UI Design (Design de Interface)', 'Design e Experiência do Usuário (UX/UI)'),
('Design Systems', 'Design e Experiência do Usuário (UX/UI)'),
('Heurísticas de Nielsen', 'Design e Experiência do Usuário (UX/UI)'),
('Princípios de Gestalt', 'Design e Experiência do Usuário (UX/UI)'),
('Teoria das Cores', 'Design e Experiência do Usuário (UX/UI)'),
('Tipografia', 'Design e Experiência do Usuário (UX/UI)'),
('Design Responsivo', 'Design e Experiência do Usuário (UX/UI)'),
('Design Mobile (iOS/Android)', 'Design e Experiência do Usuário (UX/UI)'),
('Acessibilidade (WCAG)', 'Design e Experiência do Usuário (UX/UI)'),
('Adobe Illustrator', 'Design e Experiência do Usuário (UX/UI)'),
('Adobe Photoshop', 'Design e Experiência do Usuário (UX/UI)'),
('InVision', 'Design e Experiência do Usuário (UX/UI)'),
('Microinterações', 'Design e Experiência do Usuário (UX/UI)'),
('Card Sorting', 'Design e Experiência do Usuário (UX/UI)'),
('UX Writing', 'Design e Experiência do Usuário (UX/UI)'),
('Entrevistas com Usuários', 'Design e Experiência do Usuário (UX/UI)'),
('Análise Heurística', 'Design e Experiência do Usuário (UX/UI)'),
('Design Centrado no Usuário', 'Design e Experiência do Usuário (UX/UI)'),

-- Categoria 5: Criação e Conteúdo
('Redação (Copywriting)', 'Criação e Conteúdo'),
('SEO (Otimização para Buscadores)', 'Criação e Conteúdo'),
('Marketing de Conteúdo', 'Criação e Conteúdo'),
('Storytelling', 'Criação e Conteúdo'),
('Roteirização', 'Criação e Conteúdo'),
('Edição de Vídeo (Adobe Premiere, DaVinci Resolve)', 'Criação e Conteúdo'),
('Edição de Áudio (Podcast, Adobe Audition)', 'Criação e Conteúdo'),
('Fotografia', 'Criação e Conteúdo'),
('Adobe Photoshop (Manipulação)', 'Criação e Conteúdo'),
('Adobe Illustrator (Vetorização)', 'Criação e Conteúdo'),
('Adobe InDesign (Diagramação)', 'Criação e Conteúdo'),
('Produção de Conteúdo para Mídias Sociais', 'Criação e Conteúdo'),
('Ghostwriting', 'Criação e Conteúdo'),
('Redação Técnica', 'Criação e Conteúdo'),
('Revisão de Texto (Gramática)', 'Criação e Conteúdo'),
('Motion Graphics (Adobe After Effects)', 'Criação e Conteúdo'),
('Branding (Identidade Visual)', 'Criação e Conteúdo'),
('Design Gráfico', 'Criação e Conteúdo'),
('UI Writing', 'Criação e Conteúdo'),
('Blogging', 'Criação e Conteúdo'),
('Email Marketing (Copy)', 'Criação e Conteúdo'),
('Tradução', 'Criação e Conteúdo'),
('Transcrição', 'Criação e Conteúdo'),
('Legendagem', 'Criação e Conteúdo'),
('Apresentações (PowerPoint, Google Slides)', 'Criação e Conteúdo'),
('Captação de Áudio', 'Criação e Conteúdo'),
('Captação de Imagem (Vídeo)', 'Criação e Conteúdo'),
('Direção de Arte', 'Criação e Conteúdo'),
('Pesquisa de Palavras-chave', 'Criação e Conteúdo'),
('UX Writing', 'Criação e Conteúdo'),

-- Categoria 6: Marketing Digital
('SEO/SEM', 'Marketing Digital'),
('Tráfego Pago (Google Ads)', 'Marketing Digital'),
('Social Media Ads (Facebook/Instagram Ads)', 'Marketing Digital'),
('Gestão de Mídias Sociais', 'Marketing Digital'),
('Marketing de Conteúdo', 'Marketing Digital'),
('Email Marketing', 'Marketing Digital'),
('Inbound Marketing', 'Marketing Digital'),
('Automação de Marketing (RD Station, HubSpot)', 'Marketing Digital'),
('CRM (Gestão de Relacionamento)', 'Marketing Digital'),
('Google Analytics', 'Marketing Digital'),
('Métricas (KPIs, ROAS, CPA)', 'Marketing Digital'),
('Marketing de Influência', 'Marketing Digital'),
('Copywriting', 'Marketing Digital'),
('Afiliação', 'Marketing Digital'),
('E-commerce (Gestão de Plataforma)', 'Marketing Digital'),
('Growth Hacking', 'Marketing Digital'),
('Testes A/B', 'Marketing Digital'),
('Otimização da Taxa de Conversão (CRO)', 'Marketing Digital'),
('Branding (Gestão de Marca)', 'Marketing Digital'),
('Lançamento de Produtos', 'Marketing Digital'),
('Pesquisa de Mercado', 'Marketing Digital'),
('Análise de Concorrência', 'Marketing Digital'),
('LinkedIn Ads', 'Marketing Digital'),
('TikTok Ads', 'Marketing Digital'),
('Planejamento de Mídia', 'Marketing Digital'),
('Assessoria de Imprensa', 'Marketing Digital'),
('YouTube Marketing', 'Marketing Digital'),
('Marketing de Afiliados', 'Marketing Digital'),
('Funil de Vendas', 'Marketing Digital'),
('Landing Pages', 'Marketing Digital'),

-- Categoria 7: Gestão e Administração
('Gestão de Projetos (PMBOK)', 'Gestão e Administração'),
('Planejamento Estratégico', 'Gestão e Administração'),
('Gestão Financeira (Básica)', 'Gestão e Administração'),
('Liderança de Equipes', 'Gestão e Administração'),
('Gestão de Pessoas', 'Gestão e Administração'),
('Orçamento (Budgeting)', 'Gestão e Administração'),
('Análise SWOT', 'Gestão e Administração'),
('Definição de OKRs/KPIs', 'Gestão e Administração'),
('Gestão de Processos (BPM)', 'Gestão e Administração'),
('Tomada de Decisão', 'Gestão e Administração'),
('Negociação Estratégica', 'Gestão e Administração'),
('Gestão de Riscos', 'Gestão e Administração'),
('Administração Geral', 'Gestão e Administração'),
('Gestão de Mudanças', 'Gestão e Administração'),
('Planejamento Operacional', 'Gestão e Administração'),
('Consultoria de Gestão', 'Gestão e Administração'),
('Gestão da Qualidade (ISO 9001)', 'Gestão e Administração'),
('Relacionamento com Stakeholders', 'Gestão e Administração'),
('Captação de Recursos (Fundraising)', 'Gestão e Administração'),
('Análise de Viabilidade', 'Gestão e Administração'),
('Gestão de Contratos', 'Gestão e Administração'),
('Liderança Situacional', 'Gestão e Administração'),
('Desenvolvimento de Novos Negócios', 'Gestão e Administração'),
('Gestão de Crise', 'Gestão e Administração'),
('Logística (Visão Geral)', 'Gestão e Administração'),
('Compras e Suprimentos', 'Gestão e Administração'),
('Planejamento de Demanda', 'Gestão e Administração'),
('Delegação de Tarefas', 'Gestão e Administração'),
('Empreendedorismo', 'Gestão e Administração'),
('Gerenciamento de Reuniões', 'Gestão e Administração'),

-- Categoria 8: Finanças e Contabilidade
('Contabilidade Geral', 'Finanças e Contabilidade'),
('Análise de Balanço Patrimonial', 'Finanças e Contabilidade'),
('DRE (Demonstração de Resultado)', 'Finanças e Contabilidade'),
('Fluxo de Caixa (Direto e Indireto)', 'Finanças e Contabilidade'),
('Planejamento Financeiro', 'Finanças e Contabilidade'),
('Orçamento (Budgeting/Forecasting)', 'Finanças e Contabilidade'),
('Contas a Pagar e Receber', 'Finanças e Contabilidade'),
('Auditoria (Interna/Externa)', 'Finanças e Contabilidade'),
('Compliance Fiscal', 'Finanças e Contabilidade'),
('Cálculo de Impostos (ICMS, IPI, PIS/COFINS)', 'Finanças e Contabilidade'),
('Análise de Investimentos (VPL, TIR)', 'Finanças e Contabilidade'),
('Modelagem Financeira', 'Finanças e Contabilidade'),
('Excel Avançado (Financeiro)', 'Finanças e Contabilidade'),
('Tesouraria', 'Finanças e Contabilidade'),
('Gestão de Custos', 'Finanças e Contabilidade'),
('Controladoria', 'Finanças e Contabilidade'),
('Risco Financeiro', 'Finanças e Contabilidade'),
('Valuation (Avaliação de Empresas)', 'Finanças e Contabilidade'),
('Mercado de Capitais', 'Finanças e Contabilidade'),
('Faturamento', 'Finanças e Contabilidade'),
('Conciliação Bancária', 'Finanças e Contabilidade'),
('Folha de Pagamento (Cálculo)', 'Finanças e Contabilidade'),
('Planejamento Tributário', 'Finanças e Contabilidade'),
('Análise de Crédito', 'Finanças e Contabilidade'),
('Contabilidade Gerencial', 'Finanças e Contabilidade'),
('Normas IFRS', 'Finanças e Contabilidade'),
('Due Diligence', 'Finanças e Contabilidade'),
('Relatórios Financeiros', 'Finanças e Contabilidade'),
('Contabilidade de Custos', 'Finanças e Contabilidade'),
('Análise de Viabilidade Econômica', 'Finanças e Contabilidade'),

-- Categoria 9: Vendas e Negociação
('Prospecção (Outbound)', 'Vendas e Negociação'),
('Prospecção (Inbound/SDR)', 'Vendas e Negociação'),
('Fechamento de Vendas (Closer)', 'Vendas e Negociação'),
('Negociação (Técnicas)', 'Vendas e Negociação'),
('CRM (Salesforce, HubSpot, Pipedrive)', 'Vendas e Negociação'),
('SPIN Selling', 'Vendas e Negociação'),
('Venda Consultiva', 'Vendas e Negociação'),
('Gestão de Pipeline', 'Vendas e Negociação'),
('Follow-up', 'Vendas e Negociação'),
('Cold Calling', 'Vendas e Negociação'),
('Cold Mailing', 'Vendas e Negociação'),
('Apresentação de Vendas (Pitch)', 'Vendas e Negociação'),
('Demonstração de Produto', 'Vendas e Negociação'),
('Key Account Management (Gestão de Contas Chave)', 'Vendas e Negociação'),
('Pós-venda', 'Vendas e Negociação'),
('Vendas B2B', 'Vendas e Negociação'),
('Vendas B2C', 'Vendas e Negociação'),
('Inside Sales', 'Vendas e Negociação'),
('Field Sales (Venda Externa)', 'Vendas e Negociação'),
('Cross-selling', 'Vendas e Negociação'),
('Up-selling', 'Vendas e Negociação'),
('Geração de Leads', 'Vendas e Negociação'),
('Qualificação de Leads', 'Vendas e Negociação'),
('Análise de Métricas de Vendas', 'Vendas e Negociação'),
('Relacionamento com o Cliente', 'Vendas e Negociação'),
('Rapport', 'Vendas e Negociação'),
('Contorno de Objeções', 'Vendas e Negociação'),
('Funil de Vendas', 'Vendas e Negociação'),
('Proposta Comercial', 'Vendas e Negociação'),
('Inteligência de Mercado (Vendas)', 'Vendas e Negociação'),

-- Categoria 10: Atendimento e Sucesso do Cliente
('Atendimento ao Cliente (Multicanal)', 'Atendimento e Sucesso do Cliente'),
('Suporte Técnico (Nível 1, 2)', 'Atendimento e Sucesso do Cliente'),
('Customer Success (CS)', 'Atendimento e Sucesso do Cliente'),
('Gestão de Churn (Retenção)', 'Atendimento e Sucesso do Cliente'),
('Onboarding de Clientes', 'Atendimento e Sucesso do Cliente'),
('NPS (Net Promoter Score)', 'Atendimento e Sucesso do Cliente'),
('CSAT (Customer Satisfaction Score)', 'Atendimento e Sucesso doCliente'),
('CES (Customer Effort Score)', 'Atendimento e Sucesso do Cliente'),
('Plataformas (Zendesk, Freshdesk)', 'Atendimento e Sucesso do Cliente'),
('Gestão de Crise (Cliente)', 'Atendimento e Sucesso do Cliente'),
('Comunicação Empática', 'Atendimento e Sucesso do Cliente'),
('Resolução de Problemas', 'Atendimento e Sucesso do Cliente'),
('Upselling/Cross-selling (via CS)', 'Atendimento e Sucesso do Cliente'),
('Treinamento de Clientes', 'Atendimento e Sucesso do Cliente'),
('Criação de Base de Conhecimento (FAQ)', 'Atendimento e Sucesso do Cliente'),
('Feedback de Clientes (Coleta e Análise)', 'Atendimento e Sucesso do Cliente'),
('Mapeamento da Jornada do Cliente', 'Atendimento e Sucesso do Cliente'),
('QBR (Quarterly Business Review)', 'Atendimento e Sucesso do Cliente'),
('Gestão de Contas', 'Atendimento e Sucesso do Cliente'),
('Relacionamento Interpessoal', 'Atendimento e Sucesso do Cliente'),
('Escuta Ativa', 'Atendimento e Sucesso do Cliente'),
('Gerenciamento de Reclamações', 'Atendimento e Sucesso do Cliente'),
('Help Desk', 'Atendimento e Sucesso do Cliente'),
('Chatbot (Gerenciamento)', 'Atendimento e Sucesso do Cliente'),
('SAC 4.0', 'Atendimento e Sucesso do Cliente'),
('Proatividade (CS)', 'Atendimento e Sucesso do Cliente'),
('Análise de Métricas de Suporte', 'Atendimento e Sucesso do Cliente'),
('Foco no Cliente', 'Atendimento e Sucesso do Cliente'),
('Paciência', 'Atendimento e Sucesso do Cliente'),
('CRM (foco em atendimento)', 'Atendimento e Sucesso do Cliente'),

-- Categoria 11: Recursos Humanos e Gestão de Pessoas
('Recrutamento e Seleção', 'Recursos Humanos e Gestão de Pessoas'),
('Employer Branding', 'Recursos Humanos e Gestão de Pessoas'),
('Onboarding/Integração', 'Recursos Humanos e Gestão de Pessoas'),
('Treinamento e Desenvolvimento (T&D)', 'Recursos Humanos e Gestão de Pessoas'),
('Avaliação de Desempenho', 'Recursos Humanos e Gestão de Pessoas'),
('Gestão de Clima Organizacional', 'Recursos Humanos e Gestão de Pessoas'),
('Cultura Organizacional', 'Recursos Humanos e Gestão de Pessoas'),
('Remuneração e Benefícios', 'Recursos Humanos e Gestão de Pessoas'),
('Cargos e Salários', 'Recursos Humanos e Gestão de Pessoas'),
('Folha de Pagamento', 'Recursos Humanos e Gestão de Pessoas'),
('Relações Trabalhistas (CLT)', 'Recursos Humanos e Gestão de Pessoas'),
('eSocial', 'Recursos Humanos e Gestão de Pessoas'),
('People Analytics', 'Recursos Humanos e Gestão de Pessoas'),
('Gestão de Performance', 'Recursos Humanos e Gestão de Pessoas'),
('Plano de Desenvolvimento Individual (PDI)', 'Recursos Humanos e Gestão de Pessoas'),
('Offboarding (Desligamento)', 'Recursos Humanos e Gestão de Pessoas'),
('Comunicação Interna', 'Recursos Humanos e Gestão de Pessoas'),
('Endomarketing', 'Recursos Humanos e Gestão de Pessoas'),
('Saúde e Segurança do Trabalho (SST)', 'Recursos Humanos e Gestão de Pessoas'),
('Gestão de Conflitos', 'Recursos Humanos e Gestão de Pessoas'),
('Programas de Diversidade e Inclusão', 'Recursos Humanos e Gestão de Pessoas'),
('Retenção de Talentos', 'Recursos Humanos e Gestão de Pessoas'),
('Mapeamento de Competências', 'Recursos Humanos e Gestão de Pessoas'),
('Pesquisa de Pulso', 'Recursos Humanos e Gestão de Pessoas'),
('Liderança (Desenvolvimento)', 'Recursos Humanos e Gestão de Pessoas'),
('Sistemas de RH (Folhamatic, Sênior)', 'Recursos Humanos e Gestão de Pessoas'),
('Legislação Trabalhista', 'Recursos Humanos e Gestão de Pessoas'),
('Hunting (Busca de Talentos)', 'Recursos Humanos e Gestão de Pessoas'),
('Entrevista por Competências', 'Recursos Humanos e Gestão de Pessoas'),
('Departamento Pessoal', 'Recursos Humanos e Gestão de Pessoas'),

-- Categoria 12: Operações e Logística
('Gestão da Cadeia de Suprimentos (Supply Chain)', 'Operações e Logística'),
('Gestão de Estoque (Inventário)', 'Operações e Logística'),
('Logística de Transporte', 'Operações e Logística'),
('Logística Reversa', 'Operações e Logística'),
('WMS (Warehouse Management System)', 'Operações e Logística'),
('TMS (Transportation Management System)', 'Operações e Logística'),
('PCP (Planejamento e Controle da Produção)', 'Operações e Logística'),
('Gestão de Frotas', 'Operações e Logística'),
('Otimização de Rotas', 'Operações e Logística'),
('Compras e Suprimentos', 'Operações e Logística'),
('Negociação com Fornecedores', 'Operações e Logística'),
('Gestão da Qualidade', 'Operações e Logística'),
('Six Sigma', 'Operações e Logística'),
('Lean Manufacturing', 'Operações e Logística'),
('ISO 9001', 'Operações e Logística'),
('Análise de Processos (BPMN)', 'Operações e Logística'),
('Mapeamento de Processos', 'Operações e Logística'),
('Previsão de Demanda', 'Operações e Logística'),
('Logística Internacional (Importação/Exportação)', 'Operações e Logística'),
('Facilities (Gestão de Infraestrutura)', 'Operações e Logística'),
('Manutenção Preditiva/Preventiva', 'Operações e Logística'),
('Gestão de Armazém', 'Operações e Logística'),
('Indicadores de Logística (KPIs)', 'Operações e Logística'),
('SAP (Módulo MM/SD)', 'Operações e Logística'),
('Custos Logísticos', 'Operações e Logística'),
('Auditoria de Processos', 'Operações e Logística'),
('Planejamento Operacional', 'Operações e Logística'),
('Curva ABC', 'Operações e Logística'),
('Picking e Packing', 'Operações e Logística'),
('Gestão de Contratos (Fornecedores)', 'Operações e Logística'),

-- Categoria 13: Saúde e Bem-Estar
('Primeiros Socorros', 'Saúde e Bem-Estar'),
('Cuidado ao Paciente', 'Saúde e Bem-Estar'),
('Triagem', 'Saúde e Bem-Estar'),
('Aferição de Sinais Vitais', 'Saúde e Bem-Estar'),
('Administração de Medicamentos', 'Saúde e Bem-Estar'),
('Enfermagem (Técnica)', 'Saúde e Bem-Estar'),
('Coleta de Exames', 'Saúde e Bem-Estar'),
('Nutrição (Conceitos Básicos)', 'Saúde e Bem-Estar'),
('Fisioterapia (Técnicas)', 'Saúde e Bem-Estar'),
('Psicologia (Acolhimento)', 'Saúde e Bem-Estar'),
('Ergonomia no Trabalho', 'Saúde e Bem-Estar'),
('Gestão de Saúde Ocupacional', 'Saúde e Bem-Estar'),
('Programas de Qualidade de Vida (QV)', 'Saúde e Bem-Estar'),
('Higienização e Esterilização', 'Saúde e Bem-Estar'),
('Biossegurança', 'Saúde e Bem-Estar'),
('Atendimento Pré-Hospitalar (APH)', 'Saúde e Bem-Estar'),
('Laudos (Interpretação Básica)', 'Saúde e Bem-Estar'),
('Agendamento (Sistemas de Saúde)', 'Saúde e Bem-Estar'),
('Prontuário Eletrônico', 'Saúde e Bem-Estar'),
('Telemedicina (Suporte)', 'Saúde e Bem-Estar'),
('Cuidado de Idosos', 'Saúde e Bem-Estar'),
('Cuidado Infantil', 'Saúde e Bem-Estar'),
('Massoterapia', 'Saúde e Bem-Estar'),
('Acompanhamento Terapêutico (AT)', 'Saúde e Bem-Estar'),
('Conscientização sobre Saúde Mental', 'Saúde e Bem-Estar'),
('Segurança do Paciente', 'Saúde e Bem-Estar'),
('Saúde Coletiva', 'Saúde e Bem-Estar'),
('Educação em Saúde', 'Saúde e Bem-Estar'),
('Recepção Clínica', 'Saúde e Bem-Estar'),
('Faturamento Hospitalar', 'Saúde e Bem-Estar'),

-- Categoria 14: Educação e Treinamento
('Design Instrucional (DI)', 'Educação e Treinamento'),
('Andragogia (Ensino de Adultos)', 'Educação e Treinamento'),
('Heutagogia (Autodidatismo)', 'Educação e Treinamento'),
('Criação de Conteúdo Educacional', 'Educação e Treinamento'),
('Storytelling (Educacional)', 'Educação e Treinamento'),
('Facilitação de Grupos', 'Educação e Treinamento'),
('Oratória e Apresentação', 'Educação e Treinamento'),
('Metodologias Ativas de Aprendizagem', 'Educação e Treinamento'),
('Gamificação (Gamification)', 'Educação e Treinamento'),
('Plataformas EAD (Moodle, Hotmart)', 'Educação e Treinamento'),
('LMS (Learning Management System)', 'Educação e Treinamento'),
('Tutoria Online', 'Educação e Treinamento'),
('Avaliação de Aprendizagem', 'Educação e Treinamento'),
('Elaboração de Provas e Testes', 'Educação e Treinamento'),
('Microlearning', 'Educação e Treinamento'),
('Treinamento Corporativo (T&D)', 'Educação e Treinamento'),
('Pedagogia', 'Educação e Treinamento'),
('Alfabetização', 'Educação e Treinamento'),
('Educação Inclusiva', 'Educação e Treinamento'),
('Google Classroom', 'Educação e Treinamento'),
('Mentoria', 'Educação e Treinamento'),
('Coaching', 'Educação e Treinamento'),
('Planejamento de Aula', 'Educação e Treinamento'),
('Revisão de Conteúdo Pedagógico', 'Educação e Treinamento'),
('Produção de Videoaulas', 'Educação e Treinamento'),
('Ferramentas de Autoria (Articulate, Captivate)', 'Educação e Treinamento'),
('Educação Infantil', 'Educação e Treinamento'),
('Tradução (Pedagógica)', 'Educação e Treinamento'),
('Didática', 'Educação e Treinamento'),
('Gestão Escolar', 'Educação e Treinamento'),

-- Categoria 15: Jurídico e Compliance
('LGPD (Lei Geral de Proteção de Dados)', 'Jurídico e Compliance'),
('Compliance (Conformidade)', 'Jurídico e Compliance'),
('Direito Contratual (Elaboração/Revisão)', 'Jurídico e Compliance'),
('Direito Trabalhista', 'Jurídico e Compliance'),
('Direito Tributário', 'Jurídico e Compliance'),
('Direito do Consumidor', 'Jurídico e Compliance'),
('Direito Societário', 'Jurídico e Compliance'),
('Due Diligence', 'Jurídico e Compliance'),
('Propriedade Intelectual (Marcas, Patentes)', 'Jurídico e Compliance'),
('Análise de Riscos (Jurídico)', 'Jurídico e Compliance'),
('Negociação de Contratos', 'Jurídico e Compliance'),
('Elaboração de Pareceres', 'Jurídico e Compliance'),
('Auditoria (Legal/Compliance)', 'Jurídico e Compliance'),
('Código de Conduta e Ética', 'Jurídico e Compliance'),
('Prevenção à Lavagem de Dinheiro (PLD)', 'Jurídico e Compliance'),
('Canal de Denúncias (Gestão)', 'Jurídico e Compliance'),
('Contencioso (Cível, Trabalhista)', 'Jurídico e Compliance'),
('Mediação e Arbitragem', 'Jurídico e Compliance'),
('Direito Digital', 'Jurídico e Compliance'),
('Licitações e Contratos Públicos', 'Jurídico e Compliance'),
('Societário (Abertura/Fechamento de Empresas)', 'Jurídico e Compliance'),
('Legal Operations (Legal Ops)', 'Jurídico e Compliance'),
('Software Jurídico (ProJuris, etc.)', 'Jurídico e Compliance'),
('Regulatório', 'Jurídico e Compliance'),
('Investigação Interna', 'Jurídico e Compliance'),
('Consultoria Jurídica', 'Jurídico e Compliance'),
('ESG (Ambiental, Social e Governança)', 'Jurídico e Compliance'),
('Relações Institucionais', 'Jurídico e Compliance'),
('Petições (Elaboração)', 'Jurídico e Compliance'),
('Análise de Jurisprudência', 'Jurídico e Compliance'),

-- Categoria 16: Idiomas
('Inglês (Básico)', 'Idiomas'),
('Inglês (Intermediário)', 'Idiomas'),
('Inglês (Avançado)', 'Idiomas'),
('Inglês (Fluente/Nativo)', 'Idiomas'),
('Espanhol (Básico)', 'Idiomas'),
('Espanhol (Intermediário)', 'Idiomas'),
('Espanhol (Avançado)', 'Idiomas'),
('Espanhol (Fluente/Nativo)', 'Idiomas'),
('Francês (Básico)', 'Idiomas'),
('Francês (Intermediário)', 'Idiomas'),
('Francês (Avançado)', 'Idiomas'),
('Alemão (Básico)', 'Idiomas'),
('Alemão (Intermediário)', 'Idiomas'),
('Italiano (Básico)', 'Idiomas'),
('Italiano (Intermediário)', 'Idiomas'),
('Mandarim (Básico)', 'Idiomas'),
('Mandarim (Intermediário)', 'Idiomas'),
('Japonês (Básico)', 'Idiomas'),
('Japonês (Intermediário)', 'Idiomas'),
('Libras (Língua Brasileira de Sinais)', 'Idiomas'),
('Português (Nativo)', 'Idiomas'),
('Português (Redação Avançada)', 'Idiomas'),
('Inglês (Técnico/Business)', 'Idiomas'),
('Espanhol (Técnico/Business)', 'Idiomas'),
('Tradução (Inglês-Português)', 'Idiomas'),
('Tradução (Espanhol-Português)', 'Idiomas'),
('Interpretação Simultânea', 'Idiomas'),
('Revisão de Texto (Idioma Estrangeiro)', 'Idiomas'),
('Redação (Idioma Estrangeiro)', 'Idiomas'),
('Coreano (Básico)', 'Idiomas'),

-- Categoria 17: Metodologias Ágeis
('Scrum', 'Metodologias Ágeis'),
('Kanban', 'Metodologias Ágeis'),
('Lean (Thinking/Startup)', 'Metodologias Ágeis'),
('XP (Extreme Programming)', 'Metodologias Ágeis'),
('SAFe (Scaled Agile Framework)', 'Metodologias Ágeis'),
('OKR (Objectives and Key Results)', 'Metodologias Ágeis'),
('Design Thinking', 'Metodologias Ágeis'),
('Management 3.0', 'Metodologias Ágeis'),
('Papel de Scrum Master', 'Metodologias Ágeis'),
('Papel de Product Owner (PO)', 'Metodologias Ágeis'),
('Sprints (Planejamento/Execução)', 'Metodologias Ágeis'),
('Daily Scrum', 'Metodologias Ágeis'),
('Sprint Review', 'Metodologias Ágeis'),
('Sprint Retrospective', 'Metodologias Ágeis'),
('User Stories (Histórias de Usuário)', 'Metodologias Ágeis'),
('Estimativa Ágil (Planning Poker)', 'Metodologias Ágeis'),
('Burndown Chart', 'Metodologias Ágeis'),
('Definition of Done (DoD)', 'Metodologias Ágeis'),
('Definition of Ready (DoR)', 'Metodologias Ágeis'),
('Métricas Ágeis (Lead Time, Cycle Time)', 'Metodologias Ágeis'),
('DevOps (Cultura)', 'Metodologias Ágeis'),
('CI/CD (Integração/Entrega Contínua)', 'Metodologias Ágeis'),
('Ferramentas (Jira, Trello, Asana)', 'Metodologias Ágeis'),
('Test Driven Development (TDD)', 'Metodologias Ágeis'),
('Behavior Driven Development (BDD)', 'Metodologias Ágeis'),
('Pair Programming', 'Metodologias Ágeis'),
('Agile Coaching', 'Metodologias Ágeis'),
('Gestão de Backlog', 'Metodologias Ágeis'),
('Priorização (MoSCoW)', 'Metodologias Ágeis'),
('Cerimônias Ágeis', 'Metodologias Ágeis'),

-- Categoria 18: Engenharia e Manufatura
('AutoCAD (2D/3D)', 'Engenharia e Manufatura'),
('SolidWorks', 'Engenharia e Manufatura'),
('CATIA', 'Engenharia e Manufatura'),
('Leitura e Interpretação de Desenho Técnico', 'Engenharia e Manufatura'),
('Gestão da Qualidade (Total)', 'Engenharia e Manufatura'),
('Six Sigma (Green/Black Belt)', 'Engenharia e Manufatura'),
('Lean Manufacturing', 'Engenharia e Manufatura'),
('Gestão de Produção (PCP)', 'Engenharia e Manufatura'),
('Manutenção Preditiva', 'Engenharia e Manufatura'),
('Manutenção Preventiva', 'Engenharia e Manufatura'),
('Manutenção Corretiva', 'Engenharia e Manufatura'),
('Segurança do Trabalho (NRs)', 'Engenharia e Manufatura'),
('Engenharia de Processos', 'Engenharia e Manufatura'),
('Automação Industrial (CLP/PLC)', 'Engenharia e Manufatura'),
('Robótica (Básica)', 'Engenharia e Manufatura'),
('Metrologia', 'Engenharia e Manufatura'),
('Gestão de Projetos (Engenharia)', 'Engenharia e Manufatura'),
('Orçamentação de Obras', 'Engenharia e Manufatura'),
('Planejamento de Obras', 'Engenharia e Manufatura'),
('SAP (Módulo PP/PM)', 'Engenharia e Manufatura'),
('CAD/CAM', 'Engenharia e Manufatura'),
('Simulação de Processos (Arena, etc.)', 'Engenharia e Manufatura'),
('Gestão Ambiental (ISO 14001)', 'Engenharia e Manufatura'),
('Análise de Falhas (FMEA)', 'Engenharia e Manufatura'),
('Eficiência Energética', 'Engenharia e Manufatura'),
('Engenharia de Produto', 'Engenharia e Manufatura'),
('Ferramentas da Qualidade (Ishikawa, Pareto)', 'Engenharia e Manufatura'),
('Engenharia Civil (Estrutural)', 'Engenharia e Manufatura'),
('Engenharia Elétrica (Sistemas de Potência)', 'Engenharia e Manufatura'),
('Resistência dos Materiais', 'Engenharia e Manufatura'),

-- Categoria 19: Ferramentas de Produtividade
('Microsoft Excel (Avançado)', 'Ferramentas de Produtividade'),
('Microsoft Word (Avançado)', 'Ferramentas de Produtividade'),
('Microsoft PowerPoint (Avançado)', 'Ferramentas de Produtividade'),
('Google Sheets (Avançado)', 'Ferramentas de Produtividade'),
('Google Docs (Avançado)', 'Ferramentas de Produtividade'),
('Google Slides (Avançado)', 'Ferramentas de Produtividade'),
('Microsoft Outlook (Gestão Avançada)', 'Ferramentas de Produtividade'),
('Google Agenda (Gestão Avançada)', 'Ferramentas de Produtividade'),
('Microsoft Teams', 'Ferramentas de Produtividade'),
('Slack', 'Ferramentas de Produtividade'),
('Zoom (Administração)', 'Ferramentas de Produtividade'),
('Trello (Gestão)', 'Ferramentas de Produtividade'),
('Asana (Gestão)', 'Ferramentas de Produtividade'),
('Notion (Organização)', 'Ferramentas de Produtividade'),
('Airtable', 'Ferramentas de Produtividade'),
('Power Automate (Básico)', 'Ferramentas de Produtividade'),
('VBA (Macros Excel)', 'Ferramentas de Produtividade'),
('Google Apps Script', 'Ferramentas de Produtividade'),
('SharePoint (Gestão)', 'Ferramentas de Produtividade'),
('OneDrive/Google Drive (Gestão de Arquivos)', 'Ferramentas de Produtividade'),
('Ferramentas de Mapa Mental (MindMeister, XMind)', 'Ferramentas de Produtividade'),
('Evernote/OneNote', 'Ferramentas de Produtividade'),
('Gestão de Senhas (LastPass, 1Password)', 'Ferramentas de Produtividade'),
('Ferramentas de Captura de Tela (Snagit)', 'Ferramentas de Produtividade'),
('Miro (Quadros Brancos)', 'Ferramentas de Produtividade'),
('Ferramentas de Formulário (Google Forms, Typeform)', 'Ferramentas de ProdutVagasidade'),
('Zapier (Automação Básica)', 'Ferramentas de Produtividade'),
('Gerenciadores de Tarefas (Todoist)', 'Ferramentas de Produtividade'),
('ClickUp', 'Ferramentas de Produtividade'),
('Power BI (Básico)', 'Ferramentas de Produtividade'),

-- Categoria 20: Infraestrutura de TI e Cloud
('AWS (Amazon Web Services)', 'Infraestrutura de TI e Cloud'),
('Microsoft Azure', 'Infraestrutura de TI e Cloud'),
('Google Cloud Platform (GCP)', 'Infraestrutura de TI e Cloud'),
('Administração de Redes', 'Infraestrutura de TI e Cloud'),
('Segurança de Redes', 'Infraestrutura de TI e Cloud'),
('Virtualização (VMware, Hyper-V)', 'Infraestrutura de TI e Cloud'),
('Contêineres (Docker, Kubernetes)', 'Infraestrutura de TI e Cloud'),
('DevOps', 'Infraestrutura de TI e Cloud'),
('CI/CD (Integração/Entrega Contínua)', 'Infraestrutura de TI e Cloud'),
('Terraform', 'Infraestrutura de TI e Cloud'),
('Ansible', 'Infraestrutura de TI e Cloud'),
('Administração de Servidores Linux', 'Infraestrutura de TI e Cloud'),
('Administração de Servidores Windows', 'Infraestrutura de TI e Cloud'),
('Gerenciamento de Banco de Dados (DBA)', 'Infraestrutura de TI e Cloud'),
('Arquitetura de Cloud', 'Infraestrutura de TI e Cloud'),
('Redes (TCP/IP, DNS, Roteamento)', 'Infraestrutura de TI e Cloud'),
('Firewalls', 'Infraestrutura de TI e Cloud'),
('VPN', 'Infraestrutura de TI e Cloud'),
('Monitoramento de Sistemas (Zabbix, Grafana)', 'Infraestrutura de TI e Cloud'),
('Scripting (Shell, PowerShell)', 'Infraestrutura de TI e Cloud'),
('Backup e Recuperação de Desastres', 'Infraestrutura de TI e Cloud'),
('Computação Serverless (Lambda)', 'Infraestrutura de TI e Cloud'),
('Gerenciamento de Identidade (Active Directory)', 'Infraestrutura de TI e Cloud'),
('ITIL', 'Infraestrutura de TI e Cloud'),
('Suporte Técnico (Hardware)', 'Infraestrutura de TI e Cloud'),
('Suporte Técnico (Software)', 'Infraestrutura de TI e Cloud'),
('Cabeamento Estruturado', 'Infraestrutura de TI e Cloud'),
('Balanceamento de Carga', 'Infraestrutura de TI e Cloud'),
('Migração para Nuvem', 'Infraestrutura de TI e Cloud'),
('FinOps', 'Infraestrutura de TI e Cloud');